name: "lint"
on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14' ]
      name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - uses: bahmutov/npm-install@v1
      - uses: bradennapier/eslint-plus-action@v3.4.2